pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                // Use bat for Windows
                bat 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                bat 'mvn test'
            }
            post {
                always {
                    // Archive JUnit test reports
                    junit 'target\\surefire-reports\\*.xml'
                }
            }
        }
        stage('Deliver') { 
            steps {
                // Call Windows batch script instead of sh
                bat 'jenkins\\scripts\\deliver.bat'
            }
        }
    }
}
